// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvap5PTCkBxKdv4AA0x-X9Yt9doQuq1KU',
    appId: '1:108517609354:web:f5e9ba694550958443c273',
    messagingSenderId: '108517609354',
    projectId: 'e-tourism-6ea03',
    authDomain: 'e-tourism-6ea03.firebaseapp.com',
    storageBucket: 'e-tourism-6ea03.appspot.com',
    measurementId: 'G-19BLC6KWKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmUWGzVwRwgamzTfS0kRTBgF5xRLbhHnA',
    appId: '1:108517609354:android:3c2e9ab0f20100fb43c273',
    messagingSenderId: '108517609354',
    projectId: 'e-tourism-6ea03',
    storageBucket: 'e-tourism-6ea03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ9ljx_batZY0Ysgrvo9Wqc12g9VUXeiQ',
    appId: '1:108517609354:ios:ba2ec912728d68bf43c273',
    messagingSenderId: '108517609354',
    projectId: 'e-tourism-6ea03',
    storageBucket: 'e-tourism-6ea03.appspot.com',
    iosClientId: '108517609354-usgp4b8km5ekr8cbolk0kcqa5e44lqcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ9ljx_batZY0Ysgrvo9Wqc12g9VUXeiQ',
    appId: '1:108517609354:ios:a3e9f6dcace46db643c273',
    messagingSenderId: '108517609354',
    projectId: 'e-tourism-6ea03',
    storageBucket: 'e-tourism-6ea03.appspot.com',
    iosClientId: '108517609354-s82ptupsnmjm56upp9irk32timuepbvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourism.RunnerTests',
  );
}
